### ISSUE TITLE
overbodig gebruik loc[]

### ISSUE THREAD

**Issue by tmmons** [DDI-Haaglanden/CustomerJourney#19]
Waarom wordt in onderstaande stuk soms wel loc[] gebruikt om na values te filteren, en soms niet (specifiek line 45,46 niet)?
Daarnaast is volgens mij de loc[] overbodig. Bij mij werkt bijvoorbeeld 
`df_users.dateOfBirth.values.astype('datetime64[Y]')`
zonder eerst na values te filteren

https://github.com/DDI-Haaglanden/CustomerJourney/blob/ac9ce42e86bdc0d96bd44eedf3b4a5ddc6781c02/getClientsData/__init__.py#L38-L51

**Comment by Fabianlanger** [comment]
- loc[] wordt gebruikt als je een selectie aan rijen wilt overschrijven. Zonder loc[] te gebruiken zou dat niet meer mogen lukken, gezien dat niet meer ondersteund wordt (kreeg vroeger regelmatig waarschuwingen dat het gaat verdwijnen). 
- Dat is interessant dat je niet eerst op na hoeft te filteren want ik kreeg een 'Math' error.

**Comment by tmmons** [comment]
Interessant dat jij math error krijgt. misschien doordat je niet eerst values doet? Kun je dat eens proberen?

Als je alsnog een mask gebruikt, zou ik het ook gebruiken bij gender. Dat kan in principe ook leeg zijn

**Comment by Fabianlanger** [comment]
Nee gender kan niet leeg zijn door de manier hoe dat geregistreerd is in ONS database. Als het niet bekend is, dan heeft dat een eigen nummer. Daarnaast gezien wij mannelijk en vrouwelijk eruit filteren en de rest overig maken, zouden er ook mogelijk niet ingevulde velden gewoon gevuld moeten worden.

**Comment by Fabianlanger** [comment]
jup werkt toch zonder mask. Ik weet niet meer hoe het erin is gekomen. Zal het opschonen!
