### ISSUE TITLE
nieuwe kolommen nodig

### ISSUE THREAD

**Issue by tmmons** [DDI-Haaglanden/CustomerJourney#20]
Kunnen hier een kolom met organisatie id en woonplaats worden toegevoegd? 
Daarnaast, is het overlijdensdatum of overlijdensjaar?

https://github.com/DDI-Haaglanden/CustomerJourney/blob/ac9ce42e86bdc0d96bd44eedf3b4a5ddc6781c02/initialize_projectdatabase/create_datamodel.py#L23-L31

**Comment by tmmons** [comment]
woonplaats gaan we op andere manier doen, organisatie_id lijkt me hier misschien nog wel handig

**Comment by Fabianlanger** [comment]
- Inderdaad, woonplaats kan theoretisch regelmatig veranderen, waardoor we dat op een andere manier wouden doen.
- ik dacht dat het vergelijkbaar was met organisatie_id, maar ik weet niet specifiek waarom wij dit niet hadden afgesproken om toe te voegen aan deze tabel

**Comment by tmmons** [comment]
beslissing is om kolom organisatie_id toe te voegen en te vullen in clienten

**Comment by Fabianlanger** [comment]
@tmmons betekend dit ook dat organisatie_id uit de touchpoint tabel gaat? Het is nu namelijk een eigenschap van de client en niet van de touchpoint.

**Comment by tmmons** [comment]
nee, uiteindelijk moeten clienten over organisaties heen gevolgd kunnen worden. Zoals gister besproken gebruiken we de organisatie_id uit de cliententabel niet echt, maar voor sanity checks willen we het wel hebben
