### ISSUE TITLE
onduidelijkheid verschil tussen getclientsdata en touchpointwordtclient

### ISSUE THREAD

**Issue by tmmons** [DDI-Haaglanden/CustomerJourney#28]
wanneer is welke relevant? In de ideale wereld wordt dit volgens mij 1 functie, maar ik weet niet of dat nu al gebeurd? Ik zie niet dat touchpointwordtclient getclientsdata aanroept

**Comment by Fabianlanger** [comment]
Nee hier zit een duidelijk verschil. Getclientsdata haalt alle gegevens van clienten op om de 'statische tabel' van clienten te vullen. Touchpointwordtclient gaat erom of iemand client is geworden. Het kan gebeuren dat een client tijdelijk niet client is, dat wordt dus bijgehouden via de touchpoint.

**Comment by tmmons** [comment]
oke, ik ben overtuigd
