### ISSUE TITLE
Genereer file van touchpoints die niet vertaald zijn naar hun id voor onboarding/debugging

### ISSUE THREAD

**Issue by Fabianlanger** [DDI-Haaglanden/CustomerJourney#37]
Genereer een file met relevante informatie om snel touchpoints in kaart te kunnen brengen die missen in de vertaal tabel of niet eruit gefilterd zijn. Dit is handig voor onboarding en debugging

**Comment by Fabianlanger** [comment]
https://github.com/DDI-Haaglanden/CustomerJourney/blob/40330a328532135f508ef1eb975b0bae26499636/custom/ddi.py#L143-L153

**Comment by tmmons** [comment]
@Fabianlanger deze is ook af toch?
