### ISSUE TITLE
Filters op 'logica' zorgen voor inconsistentie in de project database

### ISSUE THREAD

**Issue by Fabianlanger** [DDI-Haaglanden/CustomerJourney#46]
Met het idee dat wij alleen kloppende gegevens in de project database wouden hebben, zijn er filters toegevoegd zoals volgende: Iemand die uitstroomt met als rede dat diegene instroomt, genereert geen uitstroom touchpoint.

Dit soort filters zorgen voor inconsisttentie in de project database, bv, dat wij zagen dat er meer mensen instromen dan uitstromen. Hierop moet gezocht worden binnen de andere touchpoints, zodat deze touchpoints weg gehaald worden. Het is handiger als er gefiltert wordt tijdens de analyse, dan dat je filtert tijdens het ophalen van de gegevens.

**Comment by tmmons** [comment]
@Fabianlanger en deze kan ook dicht?
