### ISSUE TITLE
Touchpoint invalid toevoegen voor 'niet logische' touchpoints

### ISSUE THREAD

**Issue by Fabianlanger** [DDI-Haaglanden/CustomerJourney#47]
Wat in #46 wordt uitgelegd gelt ook voor de statische tabellen. Wij hebben alleen combinaties gepakt die moeten kloppen volgens logica. b.v. je kan niet naar huis gaan, genezen en overlijden tegelijkertijd. Als hier combinaties aantreffen in de bron database die niet in de publieke database staan, dan worden deze gelogged in de command line, maar dat kan natuurlijk over het hoofd gezien worden. Voorstel: Touchpoint 'invalid' toevoegen, die niet correcte touchpoints weergeeft met wat informatie, zodat daar beter naar gezocht kan worden. Deze touchpoints zijn voor analyse mogelijkheden ook heel eenfoudig om eruit te halen.

**Comment by tmmons** [comment]
@Fabianlanger en deze ook dicht toch?
